{{- if .Values.apiAccess.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "cronjob.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "cronjob.fullname" . }}
  apiGroup: ""
{{- end }}
