apiVersion: v2
name: hcloud-ccm-networks
description: Please migrate to github.com/community-tooling/charts

home: https://github.com/morremeyer/charts
sources:
  - https://github.com/hetznercloud/hcloud-cloud-controller-manager

type: application

version: 2.0.0
# renovate datasource=github-releases depName=hetznercloud/hcloud-cloud-controller-manager
appVersion: 1.16.0

maintainers:
  - name: morremeyer
  - name: ekeih
