{{- if .Values.isCronjob -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "generic.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: {{ .Values.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "generic.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- with .Values.initContainers }}
          initContainers:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.command }}
              command:
                {{ toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.args }}
              args:
                {{ toYaml . | nindent 16 }}
              {{- end }}
              {{- if or .Values.env .Values.envValueFrom }}
              env:
                {{- range $key, $value := .Values.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- range $key, $value := .Values.envValueFrom }}
                - name: {{ $key }}
                  valueFrom:
                    {{- $value | toYaml | nindent 20 }}
                {{- end }}
              {{- end }}
              volumeMounts:
                {{- if .Values.persistence.enabled }}
                - name: data
                  mountPath: {{ .Values.persistence.mountPath }}
                {{- end }}
              {{- with .Values.additionalVolumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end  }}
              ports:
                {{- toYaml .Values.ports | nindent 16 }}
              {{- with .Values.livenessProbe }}
              livenessProbe:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.readinessProbe }}
              readinessProbe:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            {{- if .Values.persistence.enabled }}
            - name: data
              persistentVolumeClaim:
                claimName: {{ include "generic.fullname" . }}
            {{- end }}
            {{- with .Values.additionalVolumes }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
{{- end -}}
