{{- range .Values.serviceMonitors -}}
{{- if .enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name | default (include "generic.fullname" $) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
  {{- with .additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .jobLabel | default $.Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" $ | nindent 6 }}
  endpoints:
    - port: {{ .port }}
      path: {{ .path }}
      {{- with .interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
{{- end }}
{{- end }}
