apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  {{- with .Values.service.annotations}}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "generic.selectorLabels" . | nindent 4 }}
  {{- if and (eq .Values.service.type "ClusterIP") (.Values.service.ip) }}
  clusterIP: {{ .Values.service.ip }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
