{{- $labels := include "namespaces.labels" . -}}
{{- range $name, $v := $.Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
{{- if $.Values.keepNamespaces }}
  annotations:
    helm.sh/resource-policy: keep
{{- end }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
