{{- $labels := include "namespaces.labels" . -}}
{{ if not .Values.disableNetworkPolicies }}
{{- range $namespaceName, $namespaceValues := $.Values.namespaces }}
{{- if not $namespaceValues.disableDefaultNetworkPolicies -}}
{{- range $defaultNetworkPolicyName, $defaultNetworkPolicy := $.Values.defaultNetworkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $defaultNetworkPolicyName }}
  namespace: {{ $namespaceName }}
  labels:
    {{- $labels | nindent 4 }}
{{- if $.Values.keepNetworkPolicies }}
  annotations:
    helm.sh/resource-policy: keep
{{- end }}
spec:
  {{- toYaml $defaultNetworkPolicy.spec | nindent 2}}
{{- end }}
{{- end }}
{{- range $networkPolicyName, $networkPolicy := $namespaceValues.networkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $networkPolicyName }}
  namespace: {{ $namespaceName }}
  labels:
    {{- $labels | nindent 4 }}
{{- if $.Values.keepNetworkPolicies }}
  annotations:
    helm.sh/resource-policy: keep
{{- end }}
spec:
  {{- toYaml $networkPolicy.spec | nindent 2}}
{{- end -}}
{{- end -}}
{{- end -}}
