{{ if not .Values.disableNetworkPolicies }}
{{- range $namespaceName, $namespaceValues := $.Values.namespaces }}
{{- if not $namespaceValues.disableDefaultNetworkPolicies -}}
{{- range $defaultNetworkPolicyName, $defaultNetworkPolicy := $.Values.defaultNetworkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $defaultNetworkPolicyName }}
  namespace: {{ $namespaceName }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- toYaml $defaultNetworkPolicy.spec | nindent 2}}
{{- end }}
{{- end }}
{{- range $networkPolicyName, $networkPolicy := $namespaceValues.networkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $networkPolicyName }}
  namespace: {{ $namespaceName }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- toYaml $networkPolicy.spec | nindent 2}}
{{- end -}}
{{- end -}}
{{- end -}}
