apiVersion: v2
name: namespaces
description: Deploy namespaces with (default) networkpolicies
type: application
version: 2.0.1
maintainers:
  - name: morremeyer
    email: charts@mor.re
  - name: ekeih
