apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "backup.fullname" . }}
  labels:
    {{- include "backup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.backupJob.schedule | quote }}
  concurrencyPolicy: {{ .Values.backupJob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.backupJob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.backupJob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "backup.selectorLabels" . | nindent 14 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backupJob.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          initContainers:
          - name: init
            image: "{{ .Values.backupJob.init.image.repository }}:{{ .Values.backupJob.init.image.tag }}"
            imagePullPolicy: {{ .Values.backupJob.init.image.pullPolicy }}
            command:
              - /bin/sh
            args:
              - -c
              - "restic -r {{ .Values.repo }} unlock || restic -r {{ .Values.repo }} init"
            envFrom:
              - secretRef:
                  name: {{ .Values.secretName }}
            {{- with .Values.backupJob.init.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          containers:
          - name: backup
            image: "{{ .Values.backupJob.backup.image.repository }}:{{ .Values.backupJob.backup.image.tag }}"
            imagePullPolicy: {{ .Values.backupJob.backup.image.pullPolicy }}
            {{- if .Values.backupJob.backup.command }}
            command:
              {{- toYaml .Values.backupJob.backup.command | nindent 14 }}
            {{- end }}
            args:
            {{- if .Values.backupJob.backup.args }}
              {{- toYaml .Values.backupJob.backup.args | nindent 14 }}
            {{- else }}
              - --no-cache
              - --verbose
              - --repo
              - {{ .Values.repo }}
              - backup
              - /data
            {{- end }}
            envFrom:
              - secretRef:
                  name: {{ .Values.secretName }}
            {{- with .Values.backupJob.env }}
            env:
              {{- toYaml . | nindent 14}}
            {{- end }}
            {{- with .Values.backupJob.backup.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- if .Values.pvc }}
            volumeMounts:
              - mountPath: "/data"
                name: data
            {{- end }}
          restartPolicy: {{ .Values.backupJob.restartPolicy }}
          {{- with .Values.backupJob.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.backupJob.affinityLabels }}
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels: {{ toYaml .Values.backupJob.affinityLabels | nindent 22 }}
                  topologyKey: "kubernetes.io/hostname"
          {{- else }}
          {{- with .Values.backupJob.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}

          {{- with .Values.backupJob.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.pvc }}
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: {{ .Values.pvc }}
          {{- end }}

