name: Helm Docs

on:
  pull_request:

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.REPO_PACKAGES_TOKEN }}

      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4
        with:
          # renovate: go-version
          go-version: 1.20.3

      - name: Install helm-docs
        # renovate: datasource=github-releases depName=norwoodj/helm-docs
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.11.0

      - name: regenerate documentation
        run: $HOME/go/bin/helm-docs

      - name: Commit updated docs
        uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # v9.1.1
        with:
          message: "docs: regenerate chart README.md"
          add: "charts/**/README.md"
          pull: "--rebase --autostash"
          author_name: Morre's Bot
          author_email: morremeyer-bot@maurice-meyer.de
