name: Helm Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v2
        with:
          # renovate: go-version
          go-version: 1.18.1

      - name: Install helm-docs
        # renovate: datasource=github-releases depName=norwoodj/helm-docs
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.8.1

      - name: regenerate documentation
        run: $HOME/go/bin/helm-docs

      # This is commented for now as it does not trigger new runs due to the push
      # coming from an action
      # - name: Commit updated docs
      #   uses: EndBug/add-and-commit@v8
      #   with:
      #     message: "docs: regenerate chart README.md"
      #     add: "charts/**/README.md"
      #     pull: "--rebase --autostash"
