name: Helm Docs

on:
  pull_request:
  push:

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v2
        with:
          # renovate: go-version
          go-version: 1.17.7

      - name: Install helm-docs
        # renovate: datasource=github-releases depName=norwoodj/helm-docs
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.7.0

      - name: regenerate documentation
        run: $HOME/go/bin/helm-docs

      - name: Commit updated docs
        uses: EndBug/add-and-commit@v8
        with:
          message: "docs: regenerate chart README.md"
          add: "charts/**/README.md"
          pull: "--rebase --autostash"
