name: Helm Docs - Skip

on:
  pull_request:

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name != 'morremeyer/charts' }}
    steps:
      - run: echo "Not a renovate PR, nothing to do"
