name: Helm Docs - Skip

on:
  pull_request:

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.name != 'charts' }}
    steps:
      - run: echo "Not a renovate PR, nothing to do"
