name: Validate renovate config

on:
  push:
    paths:
      - renovate.json

jobs:
  validate:
    name: Validate renovate config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.0.11
