name: Validate renovate config

on:
  pull_request:
    paths:
      - renovate.json

jobs:
  validate:
    name: Validate renovate config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - name: Validate
        uses: rinchsan/renovate-config-validator@1ea1e8514f6a33fdd71c40b0a5fa3512b9e7b936 # v0.0.12
