name: Update kube-prometheus-stack CRDs

on:
  pull_request:
    paths:
      - charts/kube-prometheus-stack-crds/Chart.yaml

jobs:
  update-crds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.REPO_PACKAGES_TOKEN }}

      - name: Remove CRDs
        run: rm charts/kube-prometheus-stack-crds/templates/*

      - name: Get current chart version
        id: chart_version
        run: |
          echo "CHECKOUT_REF=$(sed '/^version:/!d;s/version: //' charts/kube-prometheus-stack-crds/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Check out prometheus-community/helm-charts
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          repository: prometheus-community/helm-charts
          ref: "kube-prometheus-stack-${{ steps.chart_version.outputs.CHECKOUT_REF }}"
          path: kube-prometheus-stack-upstream

      - name: Copy CRDs
        run: cp kube-prometheus-stack-upstream/charts/kube-prometheus-stack/crds/* charts/kube-prometheus-stack-crds/templates/

      - name: Remove kube-prometheus-stack upstream clone
        run: rm -r kube-prometheus-stack-upstream

      - name: Commit updated CRDs
        uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # v9.1.1
        with:
          message: "chore(deps): update kube-prometheus-stack CRDs"
          add: "charts/kube-prometheus-stack-crds/templates/*"
          pull: "--rebase --autostash"
          author_name: Morre's Bot
          author_email: morremeyer-bot@maurice-meyer.de
