name: Update hcloud-ccm-networks

on:
  pull_request:
    paths:
      - charts/hcloud-ccm-networks/Chart.yaml
      - .github/workflows/update-hcloud-cloud-controller-manager.yml

jobs:
  update-crds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.REPO_PACKAGES_TOKEN }}

      - name: Remove files
        run: rm charts/hcloud-ccm-networks/templates/*

      - name: Download new files
        run: |
          # renovate datasource=github-releases depName=hetznercloud/hcloud-cloud-controller-manager
          export VERSION="1.13.1"
          curl -Lo charts/hcloud-ccm-networks/templates/ccm-networks.yaml https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v${VERSION}/ccm-networks.yaml
          sed -i 's/--cluster-cidr=.*"/--cluster-cidr={{ .Values.clusterCidr }}"/g' charts/hcloud-ccm-networks/templates/ccm-networks.yaml

      - name: Commit updated chart
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: "chore(deps): update hcloud-ccm-networks"
          add: "charts/hcloud-ccm-networks/*"
          pull: "--rebase --autostash"
          author_name: Morre's Bot
          author_email: morremeyer-bot@maurice-meyer.de
